export const CATEGORIES = [
  {
    name: 'Housing',
    slug: 'housing',
    icon: '🏠',
    description: 'Find PGs, hostels, flats, and apartments',
    subcategories: ['PG', 'Hostel', 'Flat', '1BHK', '2BHK', 'Studio'],
    color: '#6366F1',
    sortOrder: 1,
  },
  {
    name: 'Food & Dining',
    slug: 'food-dining',
    icon: '🍔',
    description: 'Discover local dhabas, cafes, and popular eateries',
    subcategories: ['Restaurant', 'Dhaba', 'Cafe', 'Street Food'],
    color: '#F59E0B',
    sortOrder: 2,
  },
  {
    name: 'Grocery',
    slug: 'grocery',
    icon: '🛒',
    description: 'Find supermarkets, kirana shops, and grocery hubs',
    subcategories: ['Supermarket', 'Kirana Store', 'Organic Store'],
    color: '#10B981',
    sortOrder: 3,
  },
  {
    name: 'Sabji Mandi',
    slug: 'sabji-mandi',
    icon: '🥦',
    description: 'Locate local fresh vegetable markets',
    subcategories: ['Local Mandi', 'Vegetable Shop', 'Fruit Stall'],
    color: '#059669',
    sortOrder: 4,
  },
  {
    name: 'Dairy',
    slug: 'dairy',
    icon: '🥛',
    description: 'Find milk, curd, paneer, and local dairies',
    subcategories: ['Dairy Booth', 'Milk Parlour', 'Organic Dairy'],
    color: '#3B82F6',
    sortOrder: 5,
  },
  {
    name: 'Home Services',
    slug: 'home-services',
    icon: '🛠️',
    description: 'Get electricians, plumbers, carpenters, and appliance repairs',
    subcategories: ['Electrician', 'Plumber', 'Carpenter', 'Appliance Repair', 'Mechanic'],
    color: '#EF4444',
    sortOrder: 6,
  },
  {
    name: 'Tiffin & Mess',
    slug: 'tiffin-mess',
    icon: '🍱',
    description: 'Daily home-cooked tiffin services and mess food',
    subcategories: ['Tiffin', 'Mess', 'Daily Meals'],
    color: '#EC4899',
    sortOrder: 7,
  },
  {
    name: 'Maid & Cook',
    slug: 'maid-cook',
    icon: '🧹',
    description: 'Find domestic help, home cooks, and laundry services',
    subcategories: ['Maid', 'Cook', 'House Help', 'Laundry', 'Dry Cleaner'],
    color: '#8B5CF6',
    sortOrder: 8,
  },
  {
    name: 'Gym & Fitness',
    slug: 'gym-fitness',
    icon: '💪',
    description: 'Locate gyms, yoga centers, and workout spots',
    subcategories: ['Gym', 'Yoga Center', 'Crossfit', 'Zumba'],
    color: '#111827',
    sortOrder: 9,
  },
  {
    name: 'Places to Visit',
    slug: 'places-to-visit',
    icon: '🌳',
    description: 'Explore parks, malls, monuments, and temples',
    subcategories: ['Park', 'Mall', 'Historical Site', 'Temple', 'Museum'],
    color: '#06B6D4',
    sortOrder: 10,
  },
  {
    name: 'Social & Fun',
    slug: 'social-fun',
    icon: '🎉',
    description: 'Find bars, pubs, game zones, and social clubs',
    subcategories: ['Pub', 'Bar', 'Gaming Zone', 'Club', 'Cafe Hub'],
    color: '#D946EF',
    sortOrder: 11,
  },
  {
    name: 'Local Transport',
    slug: 'transport',
    icon: '🚌',
    description: 'Information on local bus stands, metro, and auto stands',
    subcategories: ['Metro Station', 'Bus Stand', 'Auto Stand', 'Cab Service'],
    color: '#6B7280',
    sortOrder: 12,
  },
];
